name: Build and deploy RayTraceThis

env:
  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App
  RAYTRACETHIS_ANGULAR_CONTAINER_NAME: ray-trace-this-angular
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkot GitHub Repo
        uses: actions/checkout@v4

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Build and Push Image to container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          cd src/RayTraceThis.Angular
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.RAYTRACETHIS_ANGULAR_CONTAINER_NAME }}:${{ github.sha }} --file Dockerfile .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.RAYTRACETHIS_ANGULAR_CONTAINER_NAME }}:${{ github.sha }}

#  deploy:
#    permissions:
#      contents: none
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'Development'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#    steps:
#      - name: Lowercase the repo name and username
#        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

#      - name: Deploy to Azure Web App
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{ env.AZURE_WEBAPP_NAME }}
#          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
