name: Build and deploy RayTraceThis

env:
  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App
  RAYTRACETHIS_ANGULAR_CONTAINER_NAME: ray-trace-this-angular
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ closed ]
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-push-angular-app-to-container-registry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkot GitHub Repo
        uses: actions/checkout@v4

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Docker Login into Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Image to container Registry      
        run: |
          cd src/RayTraceThis.Angular
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.RAYTRACETHIS_ANGULAR_CONTAINER_NAME }}:${{ github.sha }} --file Dockerfile .
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.RAYTRACETHIS_ANGULAR_CONTAINER_NAME }}:${{ github.sha }}

  set-angular-web-app-to-new-image:
    runs-on: ubuntu-latest
    needs: [ build-and-push-angular-app-to-container-registry ]
    steps:

    - name: Login via Azure CLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update ray-trace-this-angular-web-app
      uses: azure/webapps-deploy@v3
      with: 
        app-name: ray-trace-this-angular-web-app
        images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.RAYTRACETHIS_ANGULAR_CONTAINER_NAME }}:${{ github.sha }}
